### ISSUE TITLE
Filter by brand

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/sheiley-shop-app#69]
**Description**

Add the possibility to filter by brand of the product

https://github.com/itsalb3rt/sheiley-shop-app/blob/b53ed2509d03bf20863cbb60eb0e11e1567f7058/src/views/products/list.vue#L113

**Comment by franciscoemanuel** [comment]
@itsalb3rt Working on it!

**Comment by itsalb3rt** [comment]
@franciscoemanuel Cool! Go ahead 🔥
