### ISSUE TITLE
Sidebar menu size

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/sheiley-shop-app#73]
**Describe the bug**
The sidebar menu size is not the correct for the elements inside the configuration, the text is truncated and some options missed

**To Reproduce**
1. Go to the app
2. Click on hamburger menu
3. Click on settings

**Expected behavior**
More space at the right

**Screenshots**

![image](https://user-images.githubusercontent.com/35310226/198440613-8bc4c63e-ba35-4cb0-8340-5e10e44cccd3.png)

![image](https://user-images.githubusercontent.com/35310226/198441209-34165056-e702-4100-9795-eeda4781f09c.png)

**Comment by pcabreram1234** [comment]
I can resolve this.

**Comment by itsalb3rt** [comment]
🤠 @pcabreram1234

**Comment by itsalb3rt** [comment]
Ready #78
