### ISSUE TITLE
Login form size

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/sheiley-shop-app#74]
**Description**

Add a max width to the login form, when the user enters from a desktop, the form is so big

![image](https://user-images.githubusercontent.com/35310226/198444566-abb4dc2a-4f70-46c8-93b1-948ab7ee894b.png)

**Comment by Yushmanth-reddy** [comment]
can you assign me this..

**Comment by DoritosXL** [comment]
Hey @itsalb3rt  could you please assign this to me?

**Comment by DoritosXL** [comment]
<img width="1366" alt="Screenshot 2022-10-28 at 10 25 13" src="https://user-images.githubusercontent.com/29042276/198545683-0f633a8d-9c5d-48ed-8e6c-a941ec109e26.png">

Here is how it looks with the implementation

**Comment by itsalb3rt** [comment]
Sure @DoritosXL !

**Comment by itsalb3rt** [comment]
ready #77
