### ISSUE TITLE
Register form size

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/sheiley-shop-app#75]
**Description**

Add a max width to the register form, when the user enters from a desktop, the form is so big

![image](https://user-images.githubusercontent.com/35310226/198445121-2286cc81-86ac-4987-b4c1-e2dadeb594b5.png)

**Comment by pcabreram1234** [comment]
I can resolve this

**Comment by itsalb3rt** [comment]
🔥 @pcabreram1234

**Comment by itsalb3rt** [comment]
Ready #81
