### ISSUE TITLE
Forgot password form size

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/sheiley-shop-app#76]
**Description**

Add a max width to the Forgot password form, when the user enters from a desktop, the form is so big

![image](https://user-images.githubusercontent.com/35310226/198445691-aff5b914-42ec-43fe-8c65-859f151cacf5.png)

**Comment by pcabreram1234** [comment]
I can resolve this, please assign it to me

**Comment by itsalb3rt** [comment]
Go go go! @pcabreram1234

**Comment by itsalb3rt** [comment]
Ready #81
